import { contextBridge, ipcRenderer } from 'electron'

const invoke = (channel, ...args) => ipcRenderer.invoke(channel, ...args)

contextBridge.exposeInMainWorld('api', {
  login: (data) => invoke('auth:login', data),
  changePassword: (data) => invoke('auth:change-password', data),
  setInitialPassword: (data) => invoke('auth:set-initial-password', data),
  getMotors: () => invoke('motor:get-all'),
  getMotor: (id) => invoke('motor:get-by-id', id),
  createMotor: (data) => invoke('motor:create', data),
  updateMotor: (data) => invoke('motor:update', data),
  deleteMotor: (id) => invoke('motor:delete', id),
  getOwners: (params) => invoke('owner:get-all', params),
  getOwner: (payload) => invoke('owner:get-by-id', payload),
  createOwner: (data) => invoke('owner:create', data),
  updateOwner: (data) => invoke('owner:update', data),
  deleteOwner: (id) => invoke('owner:delete', id),
  getHotels: () => invoke('hotel:get-all'),
  getHotel: (id) => invoke('hotel:get-by-id', id),
  createHotel: (data) => invoke('hotel:create', data),
  updateHotel: (data) => invoke('hotel:update', data),
  deleteHotel: (id) => invoke('hotel:delete', id),
  getHotelPayoutHistory: (data) => invoke('hotel:get-payout-history', data),
  getHotelPayoutPreview: (data) => invoke('hotel:payout-preview', data),
  payoutHotel: (data) => invoke('hotel:payout', data),
  getOwnerCommission: (data) => invoke('owner:get-commission-summary', data),
  payoutOwner: (data) => invoke('owner:payout', data),
  getPayoutPreview: (data) => invoke('owner:payout-preview', data),
  getPayoutHistory: (data) => invoke('owner:get-payout-history', data),
  getOwnerSlipPeriodMeta: (data) => invoke('owner:get-slip-period-meta', data),
  getRentals: (filters) => invoke('rental:get-all', filters),
  getRental: (id) => invoke('rental:get-by-id', id),
  createRental: (data) => invoke('rental:create', data),
  extendRental: (data) => invoke('rental:extend', data),
  swapRentalUnit: (data) => invoke('rental:swap-unit', data),
  updateRental: (data) => invoke('rental:update', data),
  deleteRental: (id) => invoke('rental:delete', id),
  completeRental: (id) => invoke('rental:complete', id),
  calculateRefund: (data) => invoke('refund:calculate', data),
  createRefund: (data) => invoke('refund:create', data),
  getExpenses: (filters) => invoke('expense:get-all', filters),
  createExpense: (data) => invoke('expense:create', data),
  deleteExpense: (id) => invoke('expense:delete', id),
  getCashAccounts: () => invoke('cash:get-accounts'),
  setCashOpeningBalance: (data) => invoke('cash:set-opening-balance', data),
  getCashTransactions: (filters) => invoke('cash:get-transactions', filters),
  getCashSummary: () => invoke('cash:get-summary'),
  addCashIncome: (data) => invoke('cash:add-income', data),
  addCashExpense: (data) => invoke('cash:add-expense', data),
  getReportSummary: (data) => invoke('report:summary', data),
  getMotorRanking: (data) => invoke('report:motor-ranking', data),
  getDailyReport: (data) => invoke('report:daily', data),
  getMotorIncomeReport: (data) => invoke('report:motor-income', data),
  getMotorExpensesReport: (data) => invoke('report:motor-expenses', data),
  getTransactionsReport: (data) => invoke('report:transactions', data),
  getOwnerCommissionReport: (data) => invoke('report:owner-commission', data),
  getOwnerSummaryReport: (data) => invoke('report:owner-summary', data),
  getFinancialReport: (data) => invoke('report:financial', data),
  getProfitLossReport: (data) => invoke('report:profit-loss', data),
  getBalanceSheetReport: (data) => invoke('report:balance-sheet', data),
  getAnnualRecap: (data) => invoke('report:annual-recap', data),
  // Dashboard
  getDashboardSummary: (data) => invoke('dashboard:summary', data),
  getDailyIncome: (data) => invoke('dashboard:daily-income', data),
  getDailyExpenses: (data) => invoke('dashboard:daily-expenses', data),
  getPaymentBreakdown: (data) => invoke('dashboard:payment-breakdown', data),
  getTopMotors: (data) => invoke('dashboard:top-motors', data),
  getExpenseCategories: (data) => invoke('dashboard:expense-categories', data),
  // System
  resetAllData: () => invoke('db:reset-all'),
  getProductionResetStatus: () => invoke('db:production-reset-status'),
  resetProductionDataOnce: () => invoke('db:production-reset-once'),
  getDevSandboxStats: () => invoke('db:dev-stats'),
  seedDevSandboxData: (data) => invoke('db:dev-seed', data),
  // Backup & Restore
  backupGdriveStatus: () => invoke('backup:gdrive-status'),
  backupGdriveConnect: () => invoke('backup:gdrive-connect'),
  backupGdriveDisconnect: () => invoke('backup:gdrive-disconnect'),
  backupCreateLocal: () => invoke('backup:create-local'),
  backupListLocal: () => invoke('backup:list-local'),
  backupRestoreLocal: (data) => invoke('backup:restore-local', data),
  backupGdriveUpload: () => invoke('backup:gdrive-upload'),
  backupGdriveList: () => invoke('backup:gdrive-list'),
  backupGdriveRestore: (data) => invoke('backup:gdrive-restore', data),
  backupGdriveDelete: (data) => invoke('backup:gdrive-delete', data),
  backupSetPassphrase: (data) => invoke('backup:set-passphrase', data),
  backupGetAutoCloseStatus: () => invoke('backup:auto-close-status'),
  backupSetAutoCloseStatus: (data) => invoke('backup:auto-close-set', data),
  onAppClosingBackupStatus: (callback) => {
    const listener = (_, payload) => callback(payload)
    ipcRenderer.on('app:auto-backup-close-state', listener)
    return () => ipcRenderer.removeListener('app:auto-backup-close-state', listener)
  },
  // Export
  previewPdf: (data) => invoke('export:preview-pdf', data),
  previewPdfWindow: (data) => invoke('export:preview-pdf-window', data),
  savePdf: (data) => invoke('export:save-pdf', data),
  saveExcel: (data) => invoke('export:save-excel', data),
  getDownloads: () => invoke('downloads:list'),
  openDownload: (id) => invoke('downloads:open', id),
  showDownloadInFolder: (id) => invoke('downloads:show-in-folder', id),
  deleteDownloadRecord: (id) => invoke('downloads:delete-record', id),
  deleteDownloadFile: (id) => invoke('downloads:delete-file', id),
  // License
  getLicenseStatus: () => invoke('license:status'),
  startTrial: () => invoke('license:start-trial'),
  activateLicense: (data) => invoke('license:activate', data),
  // Import
  importVehiclesFromXlsx: (data) => invoke('import:vehicles-from-xlsx', data),
})
